name: Release Assist Pipeline

on:
  pull_request:
    types: [labeled]


permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  use-release-assist:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    uses: UdiptaS24/Release-Assist/.github/workflows/release_assist_reusable.yaml@main